name: Gary K. Jackson
favicon: null
layout_spectrum: 0.47741
typography_spectrum: 0.52948
title: Gary K. Jackson - Graphic Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
